# This workflow will check if the incoming pull request includes any broken links

name: Check for dead links

on:
  pull_request:
    paths:
      - 'doc/**'
    branches: [master, '*.z']
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Check for broken internal links
      run: |
        cd doc
        npm i
        npm run-script check-links-local